[package]
org = "wso2"
name = "db_healthcheck_via_tailscale"
version = "0.1.0"
distribution = "2201.12.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mssql"
version = "1.14.0"

[[dependency]]
org = "ballerina"
name = "ftp"
version = "2.13.0"

[[platform.java17.dependency]]
groupId = "com.microsoft.sqlserver"
artifactId = "mssql-jdbc"
version = "12.4.2.jre11"
